- hosts: localhost
  connection: local
  vars:
    location: eastus
    plan_resource_group: ansiblewebapp1_plan
    win_plan_name: win_appplan1
    linux_plan_name: linux_appplan1
    linux_plan_resource_group: appserviceplan_test
  
  roles:
    - azure_preview_modules

  tasks:
  - name: create a windows plan
    azure_rm_appserviceplan:
        name: "{{ win_plan_name }}1"
        resource_group: "{{ plan_resource_group }}"
        location: "{{ location }}"
        sku: S1
  - name: create a windows plan with is_linux false
    azure_rm_appserviceplan:
        name: "{{ win_plan_name }}2"
        resource_group: "{{ plan_resource_group }}"
        sku: S1
        is_linux: false
        number_of_workers: 2
  - name: create a linux plan
    azure_rm_appserviceplan:
        resource_group: "{{ linux_plan_resource_group }}"
        name: "{{ linux_plan_name }}1"
        location: "{{ location }}"
        sku: S1
        is_linux: true
        number_of_workers: 1
  - name: update a windows plan sku, admin_site_name, number of workers
    azure_rm_appserviceplan:
        name: "{{ win_plan_name }}2"
        resource_group: "{{ plan_resource_group }}"
        sku: S2
        number_of_workers: 1
        admin_site_name: ssssss

  - name: update a linux plan, sku, admin_site_name and number_of_workers
    azure_rm_appserviceplan:
        resource_group: "{{ linux_plan_resource_group }}"
        name: "{{ linux_plan_name }}1"
        location: "{{ location }}"
        sku: S2
        is_linux: true
        number_of_workers: 2
