- hosts: localhost
  connection: local
  vars:
    resource_group: ansiblewebapp2
    location: eastus   
    vault_name: testvaultaaaaaa 
  
  tasks:
  - name: set azure credential
    set_fact:
      azure_client_id: ea052153-32d8-43ee-a5e0-b423d4703d98
      azure_secret: a89a7ceb-a731-423f-97e5-285716c85176
    

  - name: lookup service principal object id
    set_fact:
      object_id: "{{ lookup('azure_service_principal_attribute', azure_client_id='ea052153-32d8-43ee-a5e0-b423d4703d98', azure_secret='a89a7ceb-a731-423f-97e5-285716c85176', azure_tenant='72f988bf-86f1-41af-91ab-2d7cd011db47') }}"
      register: object_id
  
  - name: dump object_id
    debug:
      var: object_id

  - name: Prepare random number
    set_fact:
      rpfx: "{{ resource_group | hash('md5') | truncate(7, True, '') }}{{ 1000 | random }}"
      tenant_id: "{{ lookup('env','AZURE_TENANT') }}"
    run_once: yes

  - name: Create instance of Key Vault
    azure_rm_keyvault:
      resource_group: "{{ resource_group }}"
      vault_name: "{{ vault_name }}"
      enabled_for_deployment: yes
      vault_tenant: "{{ tenant_id }}"
      sku:
        name: standard
        family: A
      access_policies:
        - tenant_id: "{{ tenant_id }}"
          object_id: ea052153-32d8-43ee-a5e0-b423d4703d98
          keys:
            - get
            - list
            - update
            - create
            - import
            - delete
            - recover
            - backup
            - restore
            - encrypt
            - decrypt
            - wrapkey
            - unwrapkey
            - sign
            - verify
          secrets:
            - get
            - list
            - set
            - delete
            - recover
            - backup
            - restore
    register: output

  - name: create a kevyault key
    block:
      - azure_rm_keyvaultkey:
          keyvault_uri: https://{{ vault_name }}.vault.azure.net
          key_name: testkey 
          tags:
            testing: test
            delete: on-exit
        register: output
      - assert:
          that: output.changed
    rescue:
      - azure_rm_keyvaultkey:
          keyvault_uri: https://{{ vault_name }}.vault.azure.net
          state: absent
          key_name: testkey

  - name: delete a kevyault key
    azure_rm_keyvaultkey:
      keyvault_uri: https://{{ vault_name }}.vault.azure.net
      state: absent
      key_name: testkey
    register: output

  - assert:
      that: output.changed

  - name: Delete instance of Key Vault
    azure_rm_keyvault:
      resource_group: "{{ resource_group }}"
      vault_name: "vault{{ rpfx }}"
      state: absent

