- hosts: localhost
  connection: local
  vars:
    location: eastus
    resource_group: yungez-tm1
    profile_name: tttprofile1
    endpointname1: tttendpoint1
    endpointname2: tttendpoint2
    tmname: tttprofile1

  roles:
    - azure_preview_modules

  tasks:
  - name: create  resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"


  - name: update tm profile nochange
    azure_rm_trafficmanagerprofile:
      resource_group: "{{ resource_group }}"
      name: "{{ profile_name }}"
