- hosts: localhost
  connection: local
  vars:
    resource_group: ansiblewebapp1
    win_app_name: ansiblewindows
    linux_app_name: ansiblelinux
    vm_name: testvmss
    location: eastus
    plan_resource_group: ansiblewebapp1_plan
    win_plan_name: win_appplan1
    linux_plan_name: linux_appplan1
    linux_plan_resource_group: ansible-core-ci-prod-87c887fe-3006-43b5-8d54-3b4e8819d2b2-2
  
  roles:
    - azure_preview_modules

  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
        name: "{{ linux_plan_resource_group }}"
        location: "{{ location }}"

  # - name: Create a resource group
  #   azure_rm_resourcegroup:
  #       name: "{{ plan_resource_group }}"
  #       location: "{{ location }}"
  
  - name: set facts
    set_fact:
      linux_plan_name2: "{{ resource_group_secondary | replace('-','x'))[-8:] }}linplan"    


  - name: Create a docker web app with private acr registry
    azure_rm_webapp:
      resource_group: "{{ resource_group }}"
      name: "{{ win_app_name }}6"
      plan:
        resource_group: "{{ linux_app_plan_resource_group }}"
        name: "{{ linux_plan_name }}"
      container_settings:
        name: "ansible/ansible:ubuntu1404"
      registry_server_url: test.io
      registry_server_user: user
      registry_server_password: password
  register: output

- name: Assert the web app was created
  assert:
    that: output.changed

- name: Create a linux web app with nodejs framework
  azure_rm_webapp:
    resource_group: "{{ resource_group }}"
    name: "{{ win_app_name }}7"
    plan:
      resource_group: "{{ linux_app_plan_resource_group }}"
      name: "{{ linux_plan_name }}"
    linux_fx_version: "node|6.6"
  register: output

- name: Should be idempotent with linux web app created
  azure_rm_webapp:
    resource_group: "{{ resource_group }}"
    name: "{{ win_app_name }}7"
    plan:
      resource_group: "{{ linux_app_plan_resource_group }}"
      name: "{{ linux_plan_name }}"
    linux_fx_version: "node|6.6"
  register: output

- assert:
    that: not output.changed
    
- name: Update nodejs framework
  azure_rm_webapp:
    resource_group: "{{ resource_group }}"
    name: "{{ win_app_name }}7"
    plan:
      resource_group: "{{ linux_app_plan_resource_group }}"
      name: "{{ linux_plan_name }}"
    linux_fx_version: "node|6.9"
  register: output

- name: Assert the web app was created
  assert:
    that: output.changed

- name: Create a linux web app with deployment source github
  azure_rm_webapp:
    resource_group: "{{ resource_group }}"
    name: "{{ win_app_name }}8"
    plan:
      resource_group: "{{ linux_app_plan_resource_group }}"
      name: "{{ linux_plan_name }}"
    deployment_source:
      url: "https://github.com/test/test"
      branch: master
    scm_type: GitHub
  register: output

- name: Assert the web app was created
  assert:
    that: output.changed

- name: Delete web app
  azure_rm_webapp:
    resource_group: "{{ resource_group }}"
    name: "{{ win_app_name }}8"
    state: absent
  register: output

- name: Assert the web app was deleted
  assert:
    that: output.changed
  - name: dump output
    debug:
      var: results


