- hosts: localhost
  connection: local
  vars:
    resource_group: ansiblewebapp1
    location: eastus   
    vault_name: testvaultaaaaaa 

#  vars_files:
#    - [ vars/setupvars.yml ]

  tasks:
  - name: set fact
    set_fact:
      testvar: >
          !AZURE_KV:https://kvtesttest.vault.azure.net/:ansiblesecrets

  - name: include a var file
    include_vars: "includevars.yml"

  - name: show local var
    debug:
      var: testvar

  - name: show vars from include_vars file
    debug: 
      var: include1

#  - name: show vars from vars_file
#    debug: 
#      var: setup1 

  - name: show global  vars
    debug:
      var: global1

  - name: copy
    copy:
      content="!AZURE_KV:https://kvtesttest.vault.azure.net/:ansiblesecrets"
      dest=~/src/ansible-testapp/kvtest.txt
